return table.freeze({
	BaseFOV = 70,
	SprintFOVBonus = 6,
	AirFOVBonus = 2,
	SlideJumpFOVBonus = 6,
	SlideJumpFOVSpeedForMax = 80,
	FOVResponsiveness = 10,

	ShoulderOffset = Vector3.new(2.25, 0.45, 0),
	ShoulderResponsiveness = 14,
	DefaultShiftLocked = false,
	ShiftLockToggleKey = Enum.KeyCode.LeftControl,
	HeadLockedCameraSubjectEnabled = true,
	HeadLockedSubjectPartName = "Head",
	FirstPersonDistanceThreshold = 1,
	FirstPersonBodyVisible = true,
	FirstPersonHiddenPartNames = {
		Head = true,
		HumanoidRootPart = true,
	},
	FirstPersonTransparentPartNames = {
		Torso = true,
		UpperTorso = true,
		LowerTorso = true,
	},
	FirstPersonHideAccessories = true,
	MouseBehavior = Enum.MouseBehavior.LockCenter,
	LockMouseIconEnabled = false,

	MaxStrafeRollDegrees = 1.25,
	RollResponsiveness = 12,

	LandingSmallMinAirTime = 0.18,
	LandingHeavyMinAirTime = 0.75,
	LandingSmallShakeMagnitude = 1.2,
	LandingSmallShakeRoughness = 10,
	LandingSmallShakeFadeOutTime = 0.28,
	LandingSmallShakePositionInfluence = Vector3.new(0, 0.14, 0),
	LandingSmallShakeRotationInfluence = Vector3.new(0.8, 0, 0.25),
	LandingHeavyShakeMagnitude = 2.0,
	LandingHeavyShakeRoughness = 12,
	LandingHeavyShakeFadeOutTime = 0.36,
	LandingHeavyShakePositionInfluence = Vector3.new(0, 0.2, 0),
	LandingHeavyShakeRotationInfluence = Vector3.new(1.25, 0, 0.35),
	LandingSettleMinSpeed = 55,
	LandingSettleSpeedForMax = 100,
	LandingSettleDuration = 0.16,
	LandingSettleHorizontalMinSpeed = 55,
	LandingSettleHorizontalSpeedForMax = 100,
	LandingSettleHorizontalWeight = 0.45,
	LandingSettleVerticalWeight = 0.55,
	LandingRunoutSettleDurationScale = 1.25,
	LandingRunoutSettleIntensityScale = 0.75,
	LandingSettleMaxFOVDip = 1.25,
	LandingSettleMaxYOffset = -0.12,

	FallLagDelay = 0.35,
	FallLagFullTime = 1.1,
	MaxFallLagYOffset = 0.35,
	FallLagDownVelocityThreshold = -8,
	FallLagResponsiveness = 5,
	FallLagRecoveryResponsiveness = 16,

	DisableWhenHudFOVActive = true,
})
