return table.freeze({
	RemoteName = "DestructionScore",
	MeterFrameName = "DestructionMeter",
	UnchargedFrameName = "DestructionMeterUncharged",
	HudName = "HUD",
	ParticlePresetPath = { "Assets", "UI", "ParticlePresets", "DestructionMeter" },
	MaxScoreChipsPerEvent = 6,
	MaxRemoteValue = 250,
	BaseChipDuration = 0.46,
	ChipStaggerSeconds = 0.045,
	ProgressTweenSeconds = 0.18,
	ScoreWaveSize = 80,
	MaxCadenceWaves = 3,
	CadenceWaveDelaySeconds = 0.14,
	TierStartProgressRatio = 0.5,
	FadeInSeconds = 0.18,
	FadeOutSeconds = 0.28,
	PreChipDelaySeconds = 0.18,
	ScoreTweenSeconds = 0.28,
	BumpMergeWindowSeconds = 0.12,
	ComboGraceSeconds = 0.45,
	TierUpParticleBurst = 6,
	Tiers = {
		{
			id = "Bam",
			text = "BAM!",
			threshold = 24,
			multiplier = 1,
			decaySeconds = 4.8,
		},
		{
			id = "Pow",
			text = "POW!",
			threshold = 72,
			multiplier = 2,
			decaySeconds = 5,
		},
		{
			id = "Kapow",
			text = "KAPOW!",
			threshold = 192,
			multiplier = 4,
			decaySeconds = 5.3,
		},
		{
			id = "Bang",
			text = "BANG!",
			threshold = 480,
			multiplier = 8,
			decaySeconds = 5.7,
		},
		{
			id = "Wham",
			text = "WHAM!",
			threshold = 1152,
			multiplier = 16,
			decaySeconds = 6.3,
		},
		{
			id = "Boom",
			text = "BOOM!",
			threshold = 2688,
			multiplier = 32,
			decaySeconds = 7,
		},
		{
			id = "Godly",
			text = "GODLY!",
			threshold = 6144,
			multiplier = 64,
			decaySeconds = 8,
		},
	},
})
