return table.freeze({
	RemoteName = "DestructionScore",
	MeterFrameName = "DestructionMeter",
	UnchargedFrameName = "DestructionMeterUncharged",
	HudName = "HUD",
	ParticlePresetPath = { "Assets", "UI", "ParticlePresets", "DestructionMeter" },
	MaxScoreChipsPerEvent = 6,
	MaxRemoteValue = 250,
	BaseChipDuration = 0.46,
	ChipStaggerSeconds = 0.045,
	ProgressTweenSeconds = 0.18,
	ScoreWaveSize = 80,
	MaxCadenceWaves = 3,
	CadenceWaveDelaySeconds = 0.14,
	TierStartProgressRatio = 0.5,
	FadeInSeconds = 0.18,
	FadeOutSeconds = 0.28,
	PreChipDelaySeconds = 0.18,
	ScoreTweenSeconds = 0.28,
	BumpMergeWindowSeconds = 0.12,
	ComboGraceSeconds = 0.45,
	TierUpParticleBurst = 6,
	DefaultMotion = {
		bumpScale = 1.12,
		tierUpScale = 1.24,
		labelFlashScale = 1.35,
		tierUpLabelFlashScale = 1.55,
		rotation = 3,
		tierUpRotation = 7,
		coverMinRatio = 0.16,
		coverFlashSeconds = 0.4,
		normalParticles = 2,
		tierUpParticles = 6,
		chipArcSide = 70,
		chipArcMin = 70,
		chipArcMax = 120,
	},
	Tiers = {
		{
			id = "Bam",
			text = "BAM!",
			threshold = 24,
			multiplier = 1,
			decaySeconds = 4.8,
			motion = {
				bumpScale = 1.08,
				tierUpScale = 1.18,
				labelFlashScale = 1.22,
				tierUpLabelFlashScale = 1.42,
				rotation = 2,
				tierUpRotation = 5,
				coverMinRatio = 0.14,
				coverFlashSeconds = 0.32,
				normalParticles = 1,
				tierUpParticles = 4,
				chipArcSide = 52,
				chipArcMin = 58,
				chipArcMax = 96,
			},
		},
		{
			id = "Pow",
			text = "POW!",
			threshold = 72,
			multiplier = 2,
			decaySeconds = 5,
			motion = {
				bumpScale = 1.1,
				tierUpScale = 1.21,
				labelFlashScale = 1.28,
				tierUpLabelFlashScale = 1.5,
				rotation = 3,
				tierUpRotation = 6,
				coverMinRatio = 0.15,
				coverFlashSeconds = 0.36,
				normalParticles = 2,
				tierUpParticles = 5,
				chipArcSide = 62,
				chipArcMin = 68,
				chipArcMax = 112,
			},
		},
		{
			id = "Kapow",
			text = "KAPOW!",
			threshold = 192,
			multiplier = 4,
			decaySeconds = 5.3,
			motion = {
				bumpScale = 1.13,
				tierUpScale = 1.25,
				labelFlashScale = 1.36,
				tierUpLabelFlashScale = 1.6,
				rotation = 4,
				tierUpRotation = 7,
				coverMinRatio = 0.17,
				coverFlashSeconds = 0.4,
				normalParticles = 2,
				tierUpParticles = 6,
				chipArcSide = 76,
				chipArcMin = 78,
				chipArcMax = 128,
			},
		},
		{
			id = "Bang",
			text = "BANG!",
			threshold = 480,
			multiplier = 8,
			decaySeconds = 5.7,
			motion = {
				bumpScale = 1.16,
				tierUpScale = 1.28,
				labelFlashScale = 1.44,
				tierUpLabelFlashScale = 1.68,
				rotation = 5,
				tierUpRotation = 8,
				coverMinRatio = 0.19,
				coverFlashSeconds = 0.43,
				normalParticles = 3,
				tierUpParticles = 7,
				chipArcSide = 88,
				chipArcMin = 88,
				chipArcMax = 140,
			},
		},
		{
			id = "Wham",
			text = "WHAM!",
			threshold = 1152,
			multiplier = 16,
			decaySeconds = 6.3,
			motion = {
				bumpScale = 1.19,
				tierUpScale = 1.31,
				labelFlashScale = 1.52,
				tierUpLabelFlashScale = 1.76,
				rotation = 6,
				tierUpRotation = 9,
				coverMinRatio = 0.21,
				coverFlashSeconds = 0.46,
				normalParticles = 3,
				tierUpParticles = 8,
				chipArcSide = 102,
				chipArcMin = 98,
				chipArcMax = 154,
			},
		},
		{
			id = "Boom",
			text = "BOOM!",
			threshold = 2688,
			multiplier = 32,
			decaySeconds = 7,
			motion = {
				bumpScale = 1.22,
				tierUpScale = 1.35,
				labelFlashScale = 1.62,
				tierUpLabelFlashScale = 1.9,
				rotation = 7,
				tierUpRotation = 10,
				coverMinRatio = 0.24,
				coverFlashSeconds = 0.5,
				normalParticles = 4,
				tierUpParticles = 10,
				chipArcSide = 118,
				chipArcMin = 110,
				chipArcMax = 170,
			},
		},
		{
			id = "Godly",
			text = "GODLY!",
			threshold = 6144,
			multiplier = 64,
			decaySeconds = 8,
			motion = {
				bumpScale = 1.26,
				tierUpScale = 1.42,
				labelFlashScale = 1.72,
				tierUpLabelFlashScale = 2,
				rotation = 8,
				tierUpRotation = 12,
				coverMinRatio = 0.28,
				coverFlashSeconds = 0.56,
				normalParticles = 5,
				tierUpParticles = 12,
				chipArcSide = 136,
				chipArcMin = 124,
				chipArcMax = 190,
			},
		},
	},
})
