return table.freeze({
	WalkMoveSpeed = 18,
	SprintMoveSpeed = 24,
	CrouchMoveSpeed = 10,
	BaseTurnSpeed = 14,

	GroundAccelerationTime = 0.12,
	GroundDecelerationTime = 0.04,
	GroundFriction = 2,
	GroundFrictionWeight = 1,

	SlideStartSpeed = 42,
	SlideMaxSpeed = 56,
	SlideDownhillMaxSpeed = 66,
	SlideExitSpeed = 15,
	SlideMinDuration = 1,
	SlideMaxDuration = 2,
	SlideCooldown = 0.35,
	SlideSteerResponsiveness = 5,
	SlideFlatDecay = 6,
	SlideSlopeDownAcceleration = 42,
	SlideSlopeUpDrain = 38,
	SlideSlopeNeutralThreshold = 0.03,
	SlideEntrySpeedBonus = 18,
	SlideEntryBurstDuration = 0.16,
	SlideEntryBurstEndSpeedScale = 0.88,
	SlideEntryBurstBlockedSpeedFloor = 18,
	SlideEntryBurstBlockedTime = 0.06,
	SlideBlockedSpeedFloor = 8,
	SlideBlockedTime = 0.12,
	SlideJumpVelocityScale = 1.08,
	SlideJumpVelocityBonus = 4,
	SlideJumpMinBurstSpeed = 46,
	SlideJumpMaxSpeed = 66,
	SlideJumpGraceTime = 0.12,
	SlideJumpBurstEndSpeedScale = 0.68,
	SlideJumpBurstDuration = 0.12,
	SlideJumpBurstGroundForgiveness = 0.08,
	SlideJumpBurstBlockedSpeedFloor = 35,
	SlideJumpBurstBlockedTime = 0.06,
	SlideGroundAccelerationTime = 0.03,
	SlideGroundDecelerationTime = 0.22,
	SlideGroundFriction = 0.45,
	SlideGroundFrictionWeight = 0.35,
	AirCarryDuration = 0.75,
	AirCarryEndSpeedScale = 0.65,
	GroundRunoutExitSpeed = 24,
	GroundRunoutDrainRate = 7,
	GroundRunoutSteerResponsiveness = 9,
	GroundRunoutForwardDotThreshold = 0.35,
	GroundRunoutOppositeDotThreshold = -0.25,

	LandingRecoveryDuration = 0.16,
	LandingLowHorizontalSpeed = 28,
	LandingMediumHorizontalSpeed = 55,
	LandingHighHorizontalSpeed = 75,
	LandingMediumImpactSpeed = 45,
	LandingRunoutForwardDot = 0.45,
	LandingRunoutSideDot = -0.1,
	LandingInputGraceTime = 0.1,
	LandingRecoveryStartFrictionScale = 0.35,
	LandingRecoveryStartDecelerationScale = 2.5,
	LandingRecoveryEndFrictionScale = 1,
	LandingRecoveryEndDecelerationScale = 1,

	MoveResponsiveness = 18,
	StopResponsiveness = 60,
	FacingResponsiveness = 24,
	FaceCameraDirection = true,
	DisableHumanoidAutoRotate = true,
	AirFacingApplyWhileKnockback = false,
	AirUprightStabilizationEnabled = true,
	AirUprightMaxTiltDegrees = 2,
	AirUprightAngularVelocityDamping = 0,
	AirUprightApplyWhileKnockback = false,
	SnapGroundStop = true,

	AirMoveSpeed = 18,
	AirMoveResponsiveness = 10,
	AirStopResponsiveness = 14,
	AirControl = table.freeze({
		ApplyWhileKnockback = false,
		RisingGravityScale = 0.82,
		ApexGravityScale = 0.68,
		FallingGravityScale = 1,
		ApexVelocityThreshold = 6,
		GravityBlendVelocityRange = 10,
		FallBrakeStartSpeed = 70,
		MaxFallSpeed = 88,
		FallBrakeHardSpeed = 112,
		FallBrakeAcceleration = 140,
		FallBrakeHardAcceleration = 240,
		SoftAirSpeedCap = 68,
		ActivationHorizontalSpeed = 30,
		ForwardAirAcceleration = 80,
		SideAirAcceleration = 150,
		ReverseAirAcceleration = 220,
		LowSpeedFullControl = 35,
		HighSpeedReducedControl = 64,
		HighSpeedControlScale = 0.65,
		SoftAirBrakeAcceleration = 130,
		SoftAirBrakeSpeedRange = 45,
		GroundedUpVelocityThreshold = 12,
		LaunchGroundSuppressionTime = 0.14,
		LandingConfirmTime = 0.035,
		LaunchProfiles = table.freeze({
			Default = table.freeze({
				MinAirTime = 0.12,
			}),
			NormalJump = table.freeze({
				MinAirTime = 0.1,
			}),
			DoubleJump = table.freeze({
				MinAirTime = 0.1,
			}),
			SlideJump = table.freeze({
				MinAirTime = 0.14,
				ModifierDuration = 0.25,
				SideSteeringScale = 1.15,
			}),
			Explosive = table.freeze({
				MinAirTime = 0.4,
				LandingConfirmTime = 0.06,
				ModifierDuration = 0.25,
				OverspeedBrakeScale = 0.65,
			}),
			Knockback = table.freeze({
				MinAirTime = 0.2,
				ModifierDuration = 0.25,
				SteeringScale = 1,
				OverspeedBrakeScale = 0.75,
			}),
			JumpPad = table.freeze({
				MinAirTime = 0.24,
				ModifierDuration = 0.25,
				OverspeedBrakeScale = 0.65,
			}),
			AirBurst = table.freeze({
				MinAirTime = 0.24,
				ModifierDuration = 0.24,
				OverspeedBrakeScale = 0.7,
			}),
			GrappleHook = table.freeze({
				MinAirTime = 0.2,
				ModifierDuration = 0.3,
				SteeringScale = 1,
				OverspeedBrakeScale = 0.5,
			}),
		}),
	}),

	CoyoteTime = 0.12,
	JumpBufferTime = 0.12,
	DoubleJumpEnabled = true,
	MaxAirJumps = 1,
	DoubleJumpUpVelocity = 44,
	DoubleJumpCooldown = 0.15,
	DoubleJumpBufferTime = 0.22,
	LandingSettleTime = 0.08,
	LandingStopResponsiveness = 80,

	SpeedScreenEffect = table.freeze({
		Enabled = true,
		PresetName = "Speed",
		StartSpeed = 28,
		StrongSpeed = 42,
		StopSpeed = 24,
		MinIntensity = 0.35,
		MaxIntensity = 1,
		SpeedResponsiveness = 12,
	}),

	DebugAttributesEnabled = true,

	MinMoveMagnitude = 0.04,
})
