return table.freeze({
	WalkMoveSpeed = 18,
	SprintMoveSpeed = 24,
	CrouchMoveSpeed = 10,
	BaseTurnSpeed = 14,

	GroundAccelerationTime = 0.12,
	GroundDecelerationTime = 0.04,
	GroundFriction = 2,
	GroundFrictionWeight = 1,

	SlideStartSpeed = 42,
	SlideMaxSpeed = 56,
	SlideDownhillMaxSpeed = 66,
	SlideExitSpeed = 15,
	SlideMinDuration = 1,
	SlideMaxDuration = 2,
	SlideCooldown = 0.35,
	SlideSteerResponsiveness = 5,
	SlideFlatDecay = 6,
	SlideSlopeDownAcceleration = 42,
	SlideSlopeUpDrain = 38,
	SlideSlopeNeutralThreshold = 0.03,
	SlideEntrySpeedBonus = 18,
	SlideEntryBurstDuration = 0.16,
	SlideEntryBurstEndSpeedScale = 0.88,
	SlideEntryBurstBlockedSpeedFloor = 18,
	SlideEntryBurstBlockedTime = 0.06,
	SlideBlockedSpeedFloor = 8,
	SlideBlockedTime = 0.12,
	SlideJumpVelocityScale = 1.25,
	SlideJumpVelocityBonus = 10,
	SlideJumpMinBurstSpeed = 58,
	SlideJumpMaxSpeed = 84,
	SlideJumpGraceTime = 0.12,
	SlideJumpBurstEndSpeedScale = 0.78,
	SlideJumpBurstDuration = 0.18,
	SlideJumpBurstGroundForgiveness = 0.08,
	SlideJumpBurstBlockedSpeedFloor = 35,
	SlideJumpBurstBlockedTime = 0.06,
	SlideGroundAccelerationTime = 0.03,
	SlideGroundDecelerationTime = 0.22,
	SlideGroundFriction = 0.45,
	SlideGroundFrictionWeight = 0.35,
	AirCarryDuration = 1.15,
	AirCarryEndSpeedScale = 0.82,
	GroundRunoutExitSpeed = 24,
	GroundRunoutDrainRate = 7,
	GroundRunoutSteerResponsiveness = 9,
	GroundRunoutForwardDotThreshold = 0.35,
	GroundRunoutOppositeDotThreshold = -0.25,

	MoveResponsiveness = 18,
	StopResponsiveness = 60,
	FacingResponsiveness = 24,
	FaceCameraDirection = true,
	DisableHumanoidAutoRotate = true,
	SnapGroundStop = true,

	AirMoveSpeed = 18,
	AirMoveResponsiveness = 10,
	AirStopResponsiveness = 14,

	CoyoteTime = 0.12,
	JumpBufferTime = 0.12,
	DoubleJumpEnabled = true,
	MaxAirJumps = 1,
	DoubleJumpUpVelocity = 52,
	DoubleJumpCooldown = 0.15,
	LandingSettleTime = 0.08,
	LandingStopResponsiveness = 80,

	DebugAttributesEnabled = true,

	MinMoveMagnitude = 0.04,
})
