return table.freeze({
	WalkMoveSpeed = 18,
	SprintMoveSpeed = 24,
	CrouchMoveSpeed = 10,
	BaseTurnSpeed = 14,

	GroundAccelerationTime = 0.12,
	GroundDecelerationTime = 0.04,
	GroundFriction = 2,
	GroundFrictionWeight = 1,

	SlideStartSpeed = 42,
	SlideMaxSpeed = 56,
	SlideDownhillMaxSpeed = 66,
	SlideExitSpeed = 15,
	SlideMinDuration = 1,
	SlideMaxDuration = 2,
	SlideCooldown = 0.35,
	SlideSteerResponsiveness = 5,
	SlideFlatDecay = 6,
	SlideSlopeDownAcceleration = 42,
	SlideSlopeUpDrain = 38,
	SlideSlopeNeutralThreshold = 0.03,
	SlideEntrySpeedBonus = 18,
	SlideEntryBurstDuration = 0.16,
	SlideEntryBurstEndSpeedScale = 0.88,
	SlideEntryBurstBlockedSpeedFloor = 18,
	SlideEntryBurstBlockedTime = 0.06,
	SlideBlockedSpeedFloor = 8,
	SlideBlockedTime = 0.12,
	SlideJumpVelocityScale = 1.25,
	SlideJumpVelocityBonus = 10,
	SlideJumpMinBurstSpeed = 58,
	SlideJumpMaxSpeed = 84,
	SlideJumpGraceTime = 0.12,
	SlideJumpBurstEndSpeedScale = 0.78,
	SlideJumpBurstDuration = 0.18,
	SlideJumpBurstGroundForgiveness = 0.08,
	SlideJumpBurstBlockedSpeedFloor = 35,
	SlideJumpBurstBlockedTime = 0.06,
	SlideGroundAccelerationTime = 0.03,
	SlideGroundDecelerationTime = 0.22,
	SlideGroundFriction = 0.45,
	SlideGroundFrictionWeight = 0.35,
	AirCarryDuration = 1.15,
	AirCarryEndSpeedScale = 0.82,
	GroundRunoutExitSpeed = 24,
	GroundRunoutDrainRate = 7,
	GroundRunoutSteerResponsiveness = 9,
	GroundRunoutForwardDotThreshold = 0.35,
	GroundRunoutOppositeDotThreshold = -0.25,

	MoveResponsiveness = 18,
	StopResponsiveness = 60,
	FacingResponsiveness = 24,
	FaceCameraDirection = true,
	DisableHumanoidAutoRotate = true,
	SnapGroundStop = true,

	AirMoveSpeed = 18,
	AirMoveResponsiveness = 10,
	AirStopResponsiveness = 14,
	AirControl = table.freeze({
		RisingGravityScale = 0.55,
		ApexGravityScale = 0.32,
		FallingGravityScale = 0.7,
		ApexVelocityThreshold = 8,
		GravityBlendVelocityRange = 18,
		FallBrakeStartSpeed = 60,
		MaxFallSpeed = 75,
		FallBrakeHardSpeed = 95,
		FallBrakeAcceleration = 170,
		FallBrakeHardAcceleration = 285,
		SoftAirSpeedCap = 90,
		ForwardAirAcceleration = 45,
		SideAirAcceleration = 75,
		ReverseAirAcceleration = 105,
		LowSpeedFullControl = 35,
		HighSpeedReducedControl = 95,
		HighSpeedControlScale = 0.35,
		SoftAirBrakeAcceleration = 95,
		SoftAirBrakeSpeedRange = 45,
		GroundedUpVelocityThreshold = 12,
		LaunchGroundSuppressionTime = 0.14,
		LandingConfirmTime = 0.035,
		LandingFrictionBoostDuration = 0.08,
		LandingFrictionBoostMinImpactSpeed = 45,
		LandingFrictionBoostMinHorizontalSpeed = 60,
		LandingFrictionBoostMultiplier = 1.35,
		LandingFrictionBoostDecelerationScale = 0.65,
		LaunchProfiles = table.freeze({
			Default = table.freeze({
				MinAirTime = 0.16,
			}),
			NormalJump = table.freeze({
				MinAirTime = 0.12,
			}),
			SlideJump = table.freeze({
				MinAirTime = 0.18,
				ModifierDuration = 0.25,
				SideSteeringScale = 1.15,
			}),
			Explosive = table.freeze({
				MinAirTime = 0.4,
				LandingConfirmTime = 0.06,
				ModifierDuration = 0.25,
				OverspeedBrakeScale = 0.65,
			}),
			Knockback = table.freeze({
				MinAirTime = 0.2,
				ModifierDuration = 0.18,
				SteeringScale = 0.25,
			}),
			JumpPad = table.freeze({
				MinAirTime = 0.24,
				ModifierDuration = 0.25,
				OverspeedBrakeScale = 0.65,
			}),
		}),
	}),

	CoyoteTime = 0.12,
	JumpBufferTime = 0.12,
	DoubleJumpEnabled = true,
	MaxAirJumps = 1,
	DoubleJumpUpVelocity = 52,
	DoubleJumpCooldown = 0.15,
	LandingSettleTime = 0.08,
	LandingStopResponsiveness = 80,

	DebugAttributesEnabled = true,

	MinMoveMagnitude = 0.04,
})
